// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using Calendare.Data;
using Calendare.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calendare.Data.Migrations
{
    [DbContext(typeof(CalendareContext))]
    partial class CalendareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "collection_sub_type", new[] { "calendar_proxy_read", "calendar_proxy_write", "default", "scheduling_inbox", "scheduling_outbox", "web_push_subscription" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "collection_type", new[] { "addressbook", "calendar", "collection", "principal" });
            NpgsqlModelBuilderExtensions.UseHiLo(modelBuilder, "EntityFrameworkHiLoSequence");

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("Calendare.Data.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<BitArray>("AuthorizedMask")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("authorized_mask");

                    b.Property<BitArray>("AuthorizedProhibit")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("authorized_prohibit");

                    b.Property<CollectionSubType>("CollectionSubType")
                        .HasColumnType("collection_sub_type")
                        .HasColumnName("collection_sub_type");

                    b.Property<CollectionType>("CollectionType")
                        .HasColumnType("collection_type")
                        .HasColumnName("collection_type");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Etag")
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<BitArray>("GlobalPermit")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("global_permit");

                    b.Property<BitArray>("GlobalPermitSelf")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("global_permit_self");

                    b.Property<Instant>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("OrderBy")
                        .HasColumnType("integer")
                        .HasColumnName("order_by");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<BitArray>("OwnerMask")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("owner_mask");

                    b.Property<BitArray>("OwnerProhibit")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("owner_prohibit");

                    b.Property<string>("ParentContainerUri")
                        .HasColumnType("text")
                        .HasColumnName("parent_container_uri");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("PermanentId")
                        .HasColumnType("uuid")
                        .HasColumnName("permanent_id");

                    b.Property<int?>("PrincipalTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("principal_type_id");

                    b.Property<string>("ScheduleTransparency")
                        .HasColumnType("text")
                        .HasColumnName("schedule_transparency");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_collection");

                    b.HasAlternateKey("Uri")
                        .HasName("ak_collection_uri");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_collection_owner_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_collection_parent_id");

                    b.HasIndex("PrincipalTypeId")
                        .HasDatabaseName("ix_collection_principal_type_id");

                    b.ToTable("collection", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.HasKey("GroupId", "MemberId")
                        .HasName("pk_collection_group");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_collection_group_member_id");

                    b.ToTable("collection_group", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<int>("ActualUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actual_user_id");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<Instant>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_data");

                    b.Property<string>("ScheduleTag")
                        .HasColumnType("text")
                        .HasColumnName("schedule_tag");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.Property<string>("VObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("v_object_type");

                    b.HasKey("Id")
                        .HasName("pk_collection_object");

                    b.HasAlternateKey("Uri")
                        .HasName("ak_collection_object_uri");

                    b.HasIndex("ActualUserId")
                        .HasDatabaseName("ix_collection_object_actual_user_id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_collection_object_collection_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_collection_object_owner_id");

                    b.ToTable("collection_object", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionProperty", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("CollectionId", "Name")
                        .HasName("pk_collection_property");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_collection_property_modified_by_id");

                    b.ToTable("collection_property", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.DataMigrationDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Instant?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Instant>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk___data_migration_history");

                    b.ToTable("__data_migration_history", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.GrantRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GrantTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("grant_type_id");

                    b.Property<int>("GranteeId")
                        .HasColumnType("integer")
                        .HasColumnName("grantee_id");

                    b.Property<int>("GrantorId")
                        .HasColumnType("integer")
                        .HasColumnName("grantor_id");

                    b.Property<bool>("IsIndirect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_indirect");

                    b.Property<Instant>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<BitArray>("Privileges")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_grant_relation");

                    b.HasAlternateKey("GrantorId", "GranteeId")
                        .HasName("ak_grant_relation_grantor_id_grantee_id");

                    b.HasIndex("GrantTypeId")
                        .HasDatabaseName("ix_grant_relation_grant_type_id");

                    b.HasIndex("GranteeId")
                        .HasDatabaseName("ix_grant_relation_grantee_id");

                    b.ToTable("grant_relation", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.GrantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Confers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<BitArray>("Privileges")
                        .IsRequired()
                        .HasColumnType("bit(16)")
                        .HasColumnName("privileges");

                    b.HasKey("Id")
                        .HasName("pk_grant_type");

                    b.ToTable("grant_type", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<Instant?>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("CardVersion")
                        .HasColumnType("text")
                        .HasColumnName("card_version");

                    b.Property<int>("CollectionObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_object_id");

                    b.Property<string>("FormattedName")
                        .HasColumnType("text")
                        .HasColumnName("formatted_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("CollectionObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_address_collection_object_id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<int>("CollectionObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_object_id");

                    b.Property<Instant?>("Completed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed");

                    b.Property<Instant?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Instant?>("Dtend")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtend");

                    b.Property<Instant?>("Dtstamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtstamp");

                    b.Property<Instant?>("Dtstart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtstart");

                    b.Property<Instant?>("Due")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due");

                    b.Property<Instant?>("FirstInstanceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_instance_end");

                    b.Property<Instant?>("FirstInstanceStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_instance_start");

                    b.Property<bool>("IsScheduling")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduling");

                    b.Property<Instant?>("LastInstanceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_instance_end");

                    b.Property<Instant?>("LastInstanceStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_instance_start");

                    b.Property<Instant?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("integer")
                        .HasColumnName("organizer_id");

                    b.Property<double>("PercentComplete")
                        .HasColumnType("double precision")
                        .HasColumnName("percent_complete");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Rrule")
                        .HasColumnType("text")
                        .HasColumnName("rrule");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("Transp")
                        .HasColumnType("text")
                        .HasColumnName("transp");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_calendar");

                    b.HasIndex("CollectionObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_calendar_collection_object_id");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_calendar_organizer_id");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectCalendarAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<int?>("AttendeeId")
                        .HasColumnType("integer")
                        .HasColumnName("attendee_id");

                    b.Property<string>("AttendeeState")
                        .HasColumnType("text")
                        .HasColumnName("attendee_state");

                    b.Property<string>("AttendeeType")
                        .HasColumnType("text")
                        .HasColumnName("attendee_type");

                    b.Property<int>("CalendarId")
                        .HasColumnType("integer")
                        .HasColumnName("calendar_id");

                    b.Property<string>("CommonName")
                        .HasColumnType("text")
                        .HasColumnName("common_name");

                    b.Property<Instant?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EMail")
                        .HasColumnType("text")
                        .HasColumnName("e_mail");

                    b.Property<string>("EMailState")
                        .HasColumnType("text")
                        .HasColumnName("e_mail_state");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<Instant?>("LastDtStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_dt_stamp");

                    b.Property<int?>("LastSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_sequence");

                    b.Property<Instant?>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ParticipationStatus")
                        .HasColumnType("text")
                        .HasColumnName("participation_status");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<bool?>("Rsvp")
                        .HasColumnType("boolean")
                        .HasColumnName("rsvp");

                    b.Property<string>("ScheduleAgent")
                        .HasColumnType("text")
                        .HasColumnName("schedule_agent");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_calendar_attendee");

                    b.HasIndex("AttendeeId")
                        .HasDatabaseName("ix_calendar_attendee_attendee_id");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_calendar_attendee_calendar_id");

                    b.ToTable("calendar_attendee", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.PrincipalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_principal_type");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("ix_principal_type_label");

                    b.ToTable("principal_type", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("AuthSecret")
                        .HasColumnType("text")
                        .HasColumnName("auth_secret");

                    b.Property<string>("ClientPublicKey")
                        .HasColumnType("text")
                        .HasColumnName("client_public_key");

                    b.Property<string>("ClientPublicKeyType")
                        .HasColumnType("text")
                        .HasColumnName("client_public_key_type");

                    b.Property<string>("ContentEncoding")
                        .HasColumnType("text")
                        .HasColumnName("content_encoding");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<int>("FailCounter")
                        .HasColumnType("integer")
                        .HasColumnName("fail_counter");

                    b.Property<Instant?>("LastNotification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification");

                    b.Property<string>("PushDestinationUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("push_destination_uri");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscription");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_push_subscription_resource_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscription_user_id");

                    b.ToTable("push_subscription", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.SchedulingMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("Processed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_email");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_email");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.HasKey("Id")
                        .HasName("pk_calendar_message");

                    b.ToTable("calendar_message", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.SyncJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<int?>("CollectionObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_object_id");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Instant?>("Issued")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_sync_journal");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_sync_journal_collection_id");

                    b.HasIndex("CollectionObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_journal_collection_object_id");

                    b.ToTable("sync_journal", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.TrxJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.PrimitiveCollection<List<string>>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("request_headers");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseError")
                        .HasColumnType("text")
                        .HasColumnName("response_error");

                    b.PrimitiveCollection<List<string>>("ResponseHeaders")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("response_headers");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("Id")
                        .HasName("pk_trx_journal");

                    b.ToTable("trx_journal", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.Usr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<Instant?>("Closed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed");

                    b.Property<Instant?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DateFormatType")
                        .HasColumnType("text")
                        .HasColumnName("date_format_type");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Instant?>("EmailOk")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_ok");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<Instant?>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usr");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usr_username");

                    b.ToTable("usr", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.UsrCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Accesskey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accesskey");

                    b.Property<Instant>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CredentialTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("credential_type_id");

                    b.Property<Instant?>("LastUsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used");

                    b.Property<Instant?>("Locked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked");

                    b.Property<Instant>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Secret")
                        .HasColumnType("text")
                        .HasColumnName("secret");

                    b.Property<int>("UsrId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<Interval?>("Validity")
                        .HasColumnType("tstzrange")
                        .HasColumnName("validity");

                    b.HasKey("Id")
                        .HasName("pk_usr_credential");

                    b.HasIndex("CredentialTypeId")
                        .HasDatabaseName("ix_usr_credential_credential_type_id");

                    b.HasIndex("UsrId")
                        .HasDatabaseName("ix_usr_credential_usr_id");

                    b.HasIndex("Accesskey", "CredentialTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_usr_credential_accesskey_credential_type_id");

                    b.ToTable("usr_credential", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.UsrCredentialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_usr_credential_type");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("ix_usr_credential_type_label");

                    b.ToTable("usr_credential_type", (string)null);
                });

            modelBuilder.Entity("Calendare.Data.Models.Collection", b =>
                {
                    b.HasOne("Calendare.Data.Models.Usr", "Owner")
                        .WithMany("Collections")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_usr_owner_id");

                    b.HasOne("Calendare.Data.Models.Collection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_collection_collection_parent_id");

                    b.HasOne("Calendare.Data.Models.PrincipalType", "PrincipalType")
                        .WithMany()
                        .HasForeignKey("PrincipalTypeId")
                        .HasConstraintName("fk_collection_principal_type_principal_type_id");

                    b.Navigation("Owner");

                    b.Navigation("Parent");

                    b.Navigation("PrincipalType");
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionGroup", b =>
                {
                    b.HasOne("Calendare.Data.Models.Collection", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_group_collection_group_id");

                    b.HasOne("Calendare.Data.Models.Collection", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_group_collection_member_id");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionObject", b =>
                {
                    b.HasOne("Calendare.Data.Models.Usr", "ActualUser")
                        .WithMany()
                        .HasForeignKey("ActualUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_object_usr_actual_user_id");

                    b.HasOne("Calendare.Data.Models.Collection", "Collection")
                        .WithMany("Objects")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_object_collection_collection_id");

                    b.HasOne("Calendare.Data.Models.Usr", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_object_usr_owner_id");

                    b.Navigation("ActualUser");

                    b.Navigation("Collection");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionProperty", b =>
                {
                    b.HasOne("Calendare.Data.Models.Collection", null)
                        .WithMany("Properties")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_property_collection_collection_id");

                    b.HasOne("Calendare.Data.Models.Usr", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_property_usr_modified_by_id");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Calendare.Data.Models.GrantRelation", b =>
                {
                    b.HasOne("Calendare.Data.Models.GrantType", "GrantType")
                        .WithMany()
                        .HasForeignKey("GrantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grant_relation_grant_type_grant_type_id");

                    b.HasOne("Calendare.Data.Models.Collection", "Grantee")
                        .WithMany()
                        .HasForeignKey("GranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grant_relation_collection_grantee_id");

                    b.HasOne("Calendare.Data.Models.Collection", "Grantor")
                        .WithMany("Grants")
                        .HasForeignKey("GrantorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grant_relation_collection_grantor_id");

                    b.Navigation("GrantType");

                    b.Navigation("Grantee");

                    b.Navigation("Grantor");
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectAddress", b =>
                {
                    b.HasOne("Calendare.Data.Models.CollectionObject", "CollectionObject")
                        .WithOne("AddressItem")
                        .HasForeignKey("Calendare.Data.Models.ObjectAddress", "CollectionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_address_collection_object_collection_object_id");

                    b.Navigation("CollectionObject");
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectCalendar", b =>
                {
                    b.HasOne("Calendare.Data.Models.CollectionObject", "CollectionObject")
                        .WithOne("CalendarItem")
                        .HasForeignKey("Calendare.Data.Models.ObjectCalendar", "CollectionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_calendar_collection_object_collection_object_id");

                    b.HasOne("Calendare.Data.Models.Usr", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_usr_organizer_id");

                    b.Navigation("CollectionObject");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectCalendarAttendee", b =>
                {
                    b.HasOne("Calendare.Data.Models.Usr", "Attendee")
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_attendee_usr_attendee_id");

                    b.HasOne("Calendare.Data.Models.ObjectCalendar", "Calendar")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_attendee_calendar_calendar_id");

                    b.Navigation("Attendee");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Calendare.Data.Models.PushSubscription", b =>
                {
                    b.HasOne("Calendare.Data.Models.Collection", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscription_collection_resource_id");

                    b.HasOne("Calendare.Data.Models.Usr", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscription_usr_user_id");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calendare.Data.Models.SyncJournal", b =>
                {
                    b.HasOne("Calendare.Data.Models.Collection", "Collection")
                        .WithMany("SyncJournal")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_journal_collection_collection_id");

                    b.HasOne("Calendare.Data.Models.CollectionObject", "CollectionObject")
                        .WithOne()
                        .HasForeignKey("Calendare.Data.Models.SyncJournal", "CollectionObjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sync_journal_collection_object_collection_object_id");

                    b.Navigation("Collection");

                    b.Navigation("CollectionObject");
                });

            modelBuilder.Entity("Calendare.Data.Models.UsrCredential", b =>
                {
                    b.HasOne("Calendare.Data.Models.UsrCredentialType", "CredentialType")
                        .WithMany()
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usr_credential_usr_credential_type_credential_type_id");

                    b.HasOne("Calendare.Data.Models.Usr", "Usr")
                        .WithMany("Credentials")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usr_credential_usr_usr_id");

                    b.Navigation("CredentialType");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Calendare.Data.Models.Collection", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Grants");

                    b.Navigation("Objects");

                    b.Navigation("Properties");

                    b.Navigation("SyncJournal");
                });

            modelBuilder.Entity("Calendare.Data.Models.CollectionObject", b =>
                {
                    b.Navigation("AddressItem");

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("Calendare.Data.Models.ObjectCalendar", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Calendare.Data.Models.Usr", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
