# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: 🏭 Build executables

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: "10.x"

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          # cache: true
          # cache-dependency-path: "**/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.7.0
        with:
          updateProjectFiles: true

      - name: Build server
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Build database migration
        working-directory: Data
        run: |
          dotnet tool install dotnet-ef
          dotnet ef migrations bundle --self-contained -r linux-x64 --force -o ../artifacts/efbundle